---
networks:
  dozzle: {}
  ingress:
    name: ingress
    external: true

volumes:
  filebrowser:
    name: filebrowser_filebrowser
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=web
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    ports:
      - 18888:8080
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 48h
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: filebrowser
        target: /data
        volume:
          subpath: dozzle
    networks:
      - ingress
      - dozzle
