---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  filebrowser:
    name: filebrowser_filebrowser
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    labels:
      - traefik.enable=true
      - traefik.http.routers.dozzle.entrypoints=websecure
      - traefik.http.routers.dozzle.rule=Host(`dozzle.${DOMAIN}`)
      - traefik.http.routers.dozzle.middlewares=authentik-proxy@docker
      - traefik.http.services.dozzle.loadbalancer.server.port=8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: volume
        source: filebrowser
        target: /data
        volume:
          subpath: dozzle
    networks:
      - ingress
    restart: unless-stopped
