---
networks:
  filebrowser: {}

volumes:
  filebrowser: {}
  filebrowser_config: {}

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    labels:
      - traefik.enable=true
      - traefik.http.routers.filebrowser.entrypoints=websecure
      - traefik.http.routers.filebrowser.rule=Host(`filebrowser.${DOMAIN}`)
      - traefik.http.services.filebrowser.loadbalancer.server.port=5678
    ports:
      - 18080:8080
    environment:
      - FB_BASEURL=/
    volumes:
      - filebrowser:/data
      - filebrowser_config:/config
    networks:
      - filebrowser
    restart: always
