---
networks:
  filebrowser: {}

volumes:
  filebrowser: {}

services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser
    ports:
      - 18080:8080
    environment:
      - FB_BASEURL=/
    volumes:
      - filebrowser:/data
    networks:
      - filebrowser
    restart: always
