networks:
  flowise: {}
  database:
    name: database
    external: true
  ingress:
    name: ingress
    external: true

volumes:
  flowise: {}

services:
  flowise:
    image: flowiseai/flowise:2.1.1
    container_name: flowise
    labels:
      - traefik.enable=true
      - traefik.http.routers.flowise.tls=true
      - traefik.http.routers.flowise.service=flowise
      - traefik.http.services.flowise.loadbalancer.server.port=3000
      - traefik.http.routers.flowise.rule=Host(`flowise.${DOMAIN}`)
    ports:
      - 3000:3000
    environment:
      DATABASE_TYPE: postgres
      DATABASE_PORT: 5432
      DATABASE_HOST: postgres
      DATABASE_NAME: flowise
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - flowise:/root/.flowise
    networks:
      - flowise
      - ingress
      - database
    restart: always
