---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  portainer:
    driver: local
    driver_opts:
      type: none
      # Google Drive for Desktop
      device: ./docker_volumes/portainer
      o: bind

services:
  portainer:
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress
    restart: always
