networks:
  ingress:
    name: ingress
    external: true

volumes:
  configs:
    external: true
  certs:
    external: true
  portainer_data:

services:
  portainer:
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.tls=true
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - certs:/certs
      - configs:/configs
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingress
    restart: always
