---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  midjourney-proxy-logs: {}
  midjourney-proxy-atta: {}
  midjourney-proxy-eatt: {}
  midjourney-proxy-data: {}

services:
  midjourney-proxy:
    image: curtpark/midjourney-proxy:v7.0.1
    container_name: midjourney-proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.midjourney-proxy.entrypoints=websecure
      - traefik.http.routers.midjourney-proxy.rule=Host(`midjourney-proxy.${DOMAIN}`)
      - traefik.http.routers.midjourney-proxy.middlewares=authentik-proxy@docker
      - traefik.http.services.midjourney-proxy.loadbalancer.server.port=8080
    user: root
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - midjourney-proxy-logs:/app/logs:rw
      - midjourney-proxy-data:/app/data:rw
      - midjourney-proxy-atta:/app/wwwroot/attachments:rw
      - midjourney-proxy-eatt:/app/wwwroot/ephemeral-attachments:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - ingress
    restart: always
