---
networks:
  ingress:
    name: ingress
    external: true

services:
  monolithic:
    # port: 9888
    image: curtpark/monolithic_server:latest
    container_name: monolithic
    labels:
      - traefik.enable=false
    networks:
      - ingress
    restart: always
