# fly.toml app configuration file generated for curt-n8n on 2024-09-19T10:57:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'curt-n8n'
primary_region = 'sin'

[experimental]
  auto_rollback = true

[build]
  image = 'docker.n8n.io/n8nio/n8n:latest'

[env]
  GENERIC_TIMEZONE = 'Asia/Seoul'
  N8N_HOST = 'curt-n8n.fly.dev'
  N8N_PORT = '5678'
  TINI_SUBREAPER = 'true'
  TZ = 'Asia/Seoul'
  WEBHOOK_URL = 'https://curt-n8n.fly.dev'

[[mounts]]
  source = 'curt_n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  processes = ['app']
  internal_port = 5678
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory = '1GB'
  cpu_kind = 'shared'
  cpus = 2
