# https://docs.n8n.io/hosting/installation/server-setups/docker-compose/
# https://docs.n8n.io/hosting/configuration/environment-variables/
---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  n8n-data:
    driver: local
    driver_opts:
      type: none
      device: /Users/jinwoo.park/docker_volumes/n8n/data
      o: bind

services:
  n8n:
    image: n8nio/n8n:2.3.5
    container_name: n8n
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)
      - traefik.http.routers.n8n.middlewares=authentik-proxy@docker
      - traefik.http.services.n8n.loadbalancer.server.port=5678
    environment:
      # n8n deployment
      N8N_HOST: n8n.${DOMAIN}
      N8N_PROTOCOL: https
      N8N_PROXY_HOPS: 1
      N8N_SECURE_COOKIE: false
      WEBHOOK_URL: https://n8n.${DOMAIN}/
      # n8n task runners
      N8N_RUNNERS_ENABLED: true
      N8N_RUNNERS_MODE: external
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: 0.0.0.0
      N8N_RUNNERS_AUTH_TOKEN: ${N8N_RUNNERS_AUTH_TOKEN}
      N8N_NATIVE_PYTHON_RUNNER: true
      # smtp
      N8N_SMTP_HOST: ${N8N_SMTP_HOST}
      N8N_SMTP_PORT: ${N8N_SMTP_PORT}
      N8N_SMTP_USER: ${N8N_SMTP_USER:-${EMAIL}}
      N8N_SMTP_SENDER: ${N8N_SMTP_SENDER:-${EMAIL}}
      N8N_SMTP_PASS: ${N8N_SMTP_PASS}
      # General
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
      # 
    networks:
      - ingress
    volumes:
      - n8n-data:/home/node/.n8n
    restart: unless-stopped
    
  n8n-task-runners:
    image: n8nio/runners:2.3.5
    container_name: n8n-task-runners
    environment:
      - N8N_RUNNERS_TASK_BROKER_URI=http://n8n:5679
      - N8N_RUNNERS_AUTH_TOKEN=${N8N_RUNNERS_AUTH_TOKEN}
    depends_on:
      - n8n
    restart: unless-stopped
