# https://docs.n8n.io/hosting/installation/server-setups/docker-compose
networks:
  n8n: {}
  ingress:
    name: ingress
    external: true

volumes:
  n8n_data: {}

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.59.4
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.service=n8n
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.rule=Host(`n8n.${DOMAIN}`)
    environment:
      # N8n deployment
      N8N_PORT: 5678
      N8N_HOST: n8n.${DOMAIN}
      N8N_SMTP_HOST: ${N8N_SMTP_HOST}
      N8N_SMTP_PORT: ${N8N_SMTP_PORT}
      N8N_SMTP_USER: ${EMAIL}
      N8N_SMTP_PASS: ${N8N_SMTP_PASS}
      # General
      GENERIC_TIMEZONE: ${TIMEZONE}
      TZ: ${TIMEZONE}
    networks:
      - n8n
      - ingress
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
