# https://docs.n8n.io/hosting/installation/server-setups/docker-compose
version: "3"

networks:
  n8n: {}
  ingress:
    name: ingress
    external: true

volumes:
  n8n_data: {}
  postgres: {}

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n
      POSTGRES_DB: n8n
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - n8n
    restart: always

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.58.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.service=n8n"
      - "traefik.http.routers.n8n.rule=PathPrefix(`/n8n`)"
      - "traefik.http.routers.n8n.middlewares=n8n-pathstrip@docker"
      - "traefik.http.middlewares.n8n-pathstrip.stripprefix.prefixes=/n8n"
      - "traefik.http.middlewares.n8n-pathstrip.stripprefix.forceslash=false"
    ports:
      - "5678:5678"
    environment:
      # N8n deployment
      N8N_PORT: 5678
      N8N_PATH: /n8n/
      N8N_HOST: ${N8N_HOST}
      N8N_SECURE_COOKIE: false
      # DB
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: n8n
      DB_POSTGRESDB_PASSWORD: n8n
      # General
      GENERIC_TIMEZONE: "Asia/Seoul"
      TZ: "Asia/Seoul"
    depends_on:
      - postgres
    networks:
      - n8n
      - ingress
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always
