version: "3"

networks:
  ingress:
    name: ingress
    external: true

services:
  traefik:
    image: traefik:v3.1.2
    container_name: traefik
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - "--providers.docker=true"
      # Traefik will listen to incoming request on the port 80/443 (http/https)
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      # The HTTP port
      - 80:80
      # The HTTPS port
      - 443:443
      # The traefik dashboard port (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ingress
    restart: always
