version: "3"

networks:
  ingress:
    name: ingress
    external: true

services:
  traefik:
    image: traefik:v3.1.2
    container_name: reverse-proxy
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - "--providers.docker=true"
      # Allow HTTP access
      - "--api.insecure=true"
    ports:
      # The HTTP port
      - 80:80
      # The traefik dashboard port (enabled by --api.insecure=true)
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ingress
    restart: always
