---
networks:
  openwhisk: {}
  ingress:
    name: ingress
    external: true

services:
  controller:
    image: openwhisk/controller:368dd80
    ports:
      - "3233:3233"
    environment:
      - DB_HOST=db
    networks:
      - openwhisk
      - ingress

  invoker:
    image: openwhisk/invoker:368dd80
    privileged: true
    networks:
      - openwhisk

  db:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    networks:
      - openwhisk
