# https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml
---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  open-webui_data: {}

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    labels:
      - traefik.enable=true
      - traefik.http.routers.open-webui.entrypoints=websecure
      - traefik.http.routers.open-webui.rule=Host(`open-webui.${DOMAIN}`)
      - traefik.http.services.open-webui.loadbalancer.server.port=8080
    environment:
      - 'ENABLE_OAUTH_SIGNUP=true'
      - 'OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true'
      - 'OAUTH_PROVIDER_NAME=Authentik'
      - 'OPENID_PROVIDER_URL=https://${DOMAIN}/application/o/open-webui/.well-known/openid-configuration'
      - 'OAUTH_CLIENT_ID=${OPENWEBUI_CLIENT_ID}'
      - 'OAUTH_CLIENT_SECRET=${OPENWEBUI_CLIENT_SECRET}'
      - 'OAUTH_SCOPES=openid email profile'
      - 'OPENID_REDIRECT_URI=https://open-webui.${DOMAIN}/oauth/oidc/callback'
    networks:
      - ingress
    volumes:
      - open-webui_data:/app/backend/open-webui_data
    restart: unless-stopped
