
---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  n8n_data: {}
  filebrowser:
    name: filebrowser_filebrowser
    external: true


services:
  perplexica-frontend:
    image: curtpark/perplexica-frontend:409c811
    container_name: perplexica-frontend
    ports:
      - 3000:3000
    environment:
      # need to build with these as args.
      - NEXT_PUBLIC_API_URL=https://api.perplexica.${DOMAIN}/api
      - NEXT_PUBLIC_WS_URL=ws://api.perplexica.${DOMAIN}
    labels:
      - traefik.enable=true
      - traefik.http.routers.perplexica.entrypoints=websecure
      - traefik.http.routers.perplexica.rule=Host(`perplexica.${DOMAIN}`)
      - traefik.http.routers.perplexica.middlewares=authentik-proxy@docker
      - traefik.http.services.perplexica.loadbalancer.server.port=3000
    networks:
      - ingress
    depends_on:
      - perplexica-backend
    restart: unless-stopped

  perplexica-backend:
    image: itzcrazykns1337/perplexica-backend:main
    container_name: perplexica-backend
    ports:
      - 3001:3001
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    labels:
      - traefik.enable=true
      - traefik.http.routers.perplexica-backend.entrypoints=websecure
      - traefik.http.routers.perplexica-backend.rule=Host(`api.perplexica.${DOMAIN}`)
      - traefik.http.routers.perplexica-backend.middlewares=authentik-proxy@docker
      - traefik.http.services.perplexica-backend.loadbalancer.server.port=3001
    volumes:
      - type: volume
        source: filebrowser
        target: /home/perplexica/data
        volume:
          subpath: perplexica-data
      - type: volume
        source: filebrowser
        target: /home/perplexica/uploads
        volume:
          subpath: perplexica-uploads
      - type: volume
        source: filebrowser
        target: /home/perplexica/config.toml
        volume:
          subpath: perplexica-config.toml
    networks:
      - ingress
    restart: unless-stopped
