---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  qdrant_storage: {}
  
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    labels:
      - traefik.enable=true
      - traefik.http.routers.qdrant.entrypoints=websecure
      - traefik.http.routers.qdrant.rule=Host(`qdrant.${DOMAIN}`)
      - traefik.http.routers.qdrant.middlewares=authentik-proxy@docker
      - traefik.http.services.qdrant.loadbalancer.server.port=6333
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    networks:
      - ingress
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
