---
networks:
  ingress:
    name: ingress
    external: true

volumes:
  qdrant_storage: {}
  
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - 6333:6333
    environment:
      QDRANT__SERVICE__GRPC_PORT: 6334
      QDRANT__SERVICE__HTTP_PORT: 6333
    networks:
      - ingress
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: always
