version: "3"

volumes:
  prometheus_data:
  grafana_data:

networks:
  default:
    name: docker_default
    external: true

services:
  dozzle:
    image: amir20/dozzle:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.rule=PathPrefix(`/dozzle`)"
      - "traefik.http.routers.dozzle.service=dozzle"
      # NOTE: middleware does not work for dozzle
    container_name: dozzle
    environment:
      - DOZZLE_BASE=/dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:2.4.6-2.6.10-ubuntu20.04
    container_name: dcgm-exporter
    environment:
      - DCGM_EXPORTER_NO_HOSTNAME=1
    cap_add:
      - SYS_ADMIN
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: always

  prometheus:
    image: prom/prometheus:v2.36.1
    container_name: prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/prometheus)"
      - "traefik.http.routers.prometheus.middlewares=prometheus-pathstrip@docker"
      - "traefik.http.middlewares.prometheus-pathstrip.stripprefix.prefixes=/prometheus"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --storage.tsdb.retention.time=14d
    volumes:
      - ./configs/gpu-metrics-prometheus-config.yaml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - default-service
    restart: always

  grafana:
    image: grafana/grafana:8.5.6
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana_provisioning:/etc/grafana/provisioning:ro
      - ./configs/grafana_dashboards:/etc/dashboards:ro
    restart: always
